### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by cenkalti** [koding/kite.js#21]
I am trying to build kite-bundle.js file from the source but I get following error.
```
➜  kite.js git:(master) gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script/register'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cenk/go/src/github.com/koding/kite.js/gulpfile.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I installed coffeescript and gulp packages before I run ```gulp``` command.

**Comment by sinan** [comment]
It still thinks you don't have coffeescript though. it's weird, can you make sure that `coffee` command works as usual?

**Comment by cenkalti** [comment]
coffee command was installed but I had not run ```npm i```. After running ```npm i```, ```gulp``` command has run successfully.
